"""initial migration

Revision ID: fa56c2000b41
Revises: 
Create Date: 2025-12-03 23:14:07.705128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa56c2000b41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=128), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=64), nullable=True),
    sa.Column('gambar', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produk_nama'), ['nama'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('otp_secret', sa.String(length=32), nullable=True),
    sa.Column('otp_enabled', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('riwayat_aktivitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aktivitas', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('riwayat_aktivitas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_riwayat_aktivitas_timestamp'), ['timestamp'], unique=False)

    op.create_table('transaksi_keluar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tanggal_keluar', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaksi_keluar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaksi_keluar_tanggal_keluar'), ['tanggal_keluar'], unique=False)

    op.create_table('transaksi_masuk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('tanggal_masuk', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaksi_masuk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaksi_masuk_tanggal_masuk'), ['tanggal_masuk'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi_masuk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaksi_masuk_tanggal_masuk'))

    op.drop_table('transaksi_masuk')
    with op.batch_alter_table('transaksi_keluar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaksi_keluar_tanggal_keluar'))

    op.drop_table('transaksi_keluar')
    with op.batch_alter_table('riwayat_aktivitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_riwayat_aktivitas_timestamp'))

    op.drop_table('riwayat_aktivitas')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('produk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produk_nama'))

    op.drop_table('produk')
    # ### end Alembic commands ###
